name: Test_Minuto_Supabase

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: 

jobs:
  test-call:
    runs-on: ubuntu-latest
    steps:
      - name: Llamada de prueba
        run: |
          curl -i -X GET "https://pmbxyfketmuzocpllvf.supabase.co/functions/v1/asist_reporte_resumen?turno=e1" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
