name: Test_Minuto_Supabase

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: # Esto activa el botón "Run workflow" para probar ya mismo

jobs:
  test-call:
    runs-on: ubuntu-latest
    steps:
      - name: Llamada a la Edge Function
        run: |
          curl -i -X GET "https://pmbxyfketmuzocepllvf.supabase.co/functions/v1/asist_reporte_resumen"
