name: Test_Minuto_Supabase

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: 

jobs:
  test-call:
    runs-on: ubuntu-latest
    steps:
      - name: Llamada de prueba
        run: |
          curl -i -X POST 'https://pmbxyfketmuzocepllvf.supabase.co/functions/v1/asist_reporte_resumen' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}' \
          -d '{"turno": "e1"}'
